events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from account import views


urlpatterns = [
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
    
    #Account links
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('account/',  views.account_view, name='account'),
    path('must_authenticate/',  views.must_authenticate_view, name='must_authenticate'),

    
    #Password reset links
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete'), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

from events.models import Event

class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have a username")
        # if not first_name:
            # raise ValueError("User must have a first name")
        # if not last_name:
            # raise ValueError("User must have a last name")
            
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
            
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self, email, username, password):
        user = self.create_user(
                email=self.normalize_email(email),
                password=password,
                username=username,
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

class Account(AbstractBaseUser):
    email           = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username        = models.CharField(max_length=30, unique=True)
    date_joined     = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login      = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin        = models.BooleanField(default=False)
    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_superuser    = models.BooleanField(default=False)
    # first_name      = models.CharField(max_length=30)
    # last_name       = models.CharField(max_length=30)
    events           = models.ManyToManyField(Event)

    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]
    
    objects = MyAccountManager()
    
    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True

events/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.core.exceptions import ValidationError
import datetime

# from account.models import Account

def upload_location(instance, filename, **kwargs):
    file_path = 'events/{host_id}/{filename}'.format(
        host_id=str(instance.host.id), filename=filename
    )
    return file_path

class Event(models.Model):
    title           = models.CharField(max_length=50)
    datetime        = models.DateTimeField()
    location        = models.CharField(max_length=100)
    description     = models.TextField(max_length=200)
    image           = models.ImageField(upload_to=upload_location)
    host            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # attendees       = models.ManyToManyField(Account)
    min_attendees   = models.IntegerField()
    max_attendees   = models.IntegerField()
    
    
    def __str__(self):
        return self.title
    
    def clean_date(self):
        date = self.cleaned_data['date']
        if date < datetime.now():
            raise ValidationError("The date cannot be in the past!")
        return date
        
@receiver(models.signals.post_delete, sender=Event)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    
    
    

events/forms.py
from django import forms

from .models import Event


class CreateEventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['title', 'datetime', 'location', 'description', 'image', 'min_attendees', 'max_attendees',]
        

class EditEventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ['title', 'datetime', 'location', 'description', 'image', 'min_attendees', 'max_attendees',]
    
    def save(self, commit=True):
        event = self.instance
        event.title = self.cleaned_data['title']
        event.datetime = self.cleaned_data['datetime']
        event.location = self.cleaned_data['location']
        event.description = self.cleaned_data['description']
        event.min_attendees = self.cleaned_data['min_attendees']
        event.max_attendees = self.cleaned_data['max_attendees']

        if self.cleaned_data['image']:
            event.image = self.cleaned_data['image']
            
        if commit:
            event.save()
            
        return event
        

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q
from django.core import paginator
from django.contrib import messages

from account.models import Account
from .models import Event
from .forms import CreateEventForm, EditEventForm

EVENTS_PER_PAGE = 1

def index(request):
    context = {}
    query =  ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)
        
    upcoming_event_list = get_event_queryset(query)
    
    #Pagination
    page = request.GET.get('page', 1)
    events_paginator = paginator.Paginator(upcoming_event_list, EVENTS_PER_PAGE)
    
    try:
        upcoming_event_list = events_paginator.page(page)
    except paginator.PageNotAnInteger:
        upcoming_event_list = events_paginator.page(EVENTS_PER_PAGE)
    except paginator.EmptyPage:
        upcoming_event_list = events_paginator.page(events_paginator.num_pages)
    
    context['upcoming_event_list'] = upcoming_event_list
    
    return render(request, 'events/index.html', context)
    
def detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    context = {
        'event': event,
    }
    
    user = request.user

    if request.POST.get("join"):
        if not user.is_authenticated:
            return redirect('must_authenticate')
        if not event.account_set.filter(pk=user.pk).exists():
            event.account_set.add(user)
        
    if request.POST.get("leave"):
        if not user.is_authenticated:
            return redirect('must_authenticate')
        if event.account_set.filter(pk=user.pk).exists():
            event.account_set.remove(user)

        else:
            context['already_playing_message'] = "You are already playing"
            
    return render(request, 'events/detail.html', context)
    
def create(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
        
    form = CreateEventForm(request.POST or None, request.FILES or None,)
    if form.is_valid():
        obj = form.save(commit=False)
        host = Account.objects.filter(email=user.email).first()
        obj.host = host
        obj.save()
        messages.success(request, "Event Created")
        form = CreateEventForm()
        
        if request.POST.get("host_attend", ""):
            obj.account_set.add(user)
            
        return redirect('account')
        
    context['form'] = form
        
    return render(request, 'events/create.html', context)


def edit(request, pk):
    
    context = {}
    
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
 
    event = get_object_or_404(Event, pk=pk)
    
    if event.host != user:
        return HttpResponse("You are not authorized to edit this event.")
    
    if request.POST:
        form = EditEventForm(request.POST or None, request.FILES or None, instance=event)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            messages.success(request, "Updated Event")
            event = obj
            
        return redirect('account')
            
    form = EditEventForm(
        initial = {
            "title":            event.title,
            "datetime":         event.datetime,
            "location":         event.location,
            "description":      event.description,
            "image":            event.image,
            "min_attendees":    event.min_attendees,
            "max_attendees":    event.max_attendees,
        }
    )
    context['form'] = form
    
    return render(request, 'events/edit.html', context)

def delete(request, pk):
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
 
    event = get_object_or_404(Event, pk=pk)
    if event.host != user:
        return HttpResponse("You are not authorized to delete this event.")
    
    if request.POST:
        event.delete()
    
    return redirect('account')
    
    
def get_event_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        events = Event.objects.filter(datetime__gte=timezone.now()).filter(
                Q(title__icontains=q) | 
                Q(description__icontains=q) |
                Q(location__icontains=q) |
                Q(datetime__icontains=q)
            ).distinct().order_by('datetime')
        
        for event in events:
            queryset.append(event)
            
    return list(set(queryset))

events/templates/events/create.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- Title -->
				<div class="form-group">
					<label for="title">Title</label>
					<input class="form-control" type="text" name="title" id="title" placeholder="Title" required autofocus>
				</div>
				
				<!-- Datetime -->
				<div class="form-group">
					<label for="datetime">Date and time</label>
					<input class="form-control" type="datetime-local" name="datetime" id="datetime" required autofocus>
				</div>
				<!-- must make only future -->
				
				<!-- Location -->
				<div class="form-group">
					<label for="location">Location</label>
					<input class="form-control" type="text" name="location" id="location" placeholder="Location" required autofocus>
				</div>

				<!-- Description -->
				<div class="form-group">
					<label for="description">Desctiption</label>
					<textarea class="form-control" rows="5" type="text" name="description" id="description" placeholder="Add a description about your event"></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="image">Image</label>
					<input  type="file" name="image" id="image" accept="image/*" required>
				</div>
				
				<!-- Min_attendees -->
				<div class="form-group">
					<label for="min_attendees">Minimum number of attendees</label>
					<input class="form-control" type="number" name="min_attendees" id="min_attendees" min="1" oninput="changeMaxAttendeesMinVal()" required autofocus>
				</div>
				
				<!-- Max_attendees -->
				<div class="form-group">
					<label for="max_attendees">Maximum number of attendees</label>
					<input class="form-control" type="number" name="max_attendees" id="max_attendees" min="1" required autofocus>
				</div>

				<!-- Is Host Attending -->
				<div class="form-group">
					<label for="host_attend">Attend?</label>
					<input class="form-control" type="checkbox" name="host_attend" id="host_attend" autofocus>
				</div>

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Create Event</button>
			</form>
		</div>
	</div>
</div>

<script>
	function changeMaxAttendeesMinVal(){
		var minVal = document.getElementById("min_attendees").value;
		document.getElementById("max_attendees").min = minVal;
		<!-- if (document.getElementById("max_attendees").value < minVal){ -->
			<!-- document.getElementById("max_attendees").value = minVal; -->
		<!-- } -->
	}
</script>
				
{% endblock content %}

events/templates/events/detail.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">
	
	.card{
		max-width: 700px;
	}
	
	.container{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row"> 
		
		<!-- Event Detail -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{event.image.url}}">
			<div class="card-body my-2">
				<h2 class="card-title">{{ event.title }}</h2>
				<p class="card-text"><strong>Location: </strong>{{ event.location }}</p>
				<p class="card-text"><strong>Date: </strong>{{ event.datetime }}<p>
				<p class="card-text">{{ event.description }}</p>
				<p><strong>Players:</strong> (max {{ event.max_attendees }} players)</p>
				<ul>
					{% for account in event.account_set.all %}
						<li>{{ account.username }}</li>
					{% endfor %}
				</ul>
				
				{% if request.user in event.account_set.all %}
					<p style="color: green;">You are attending this event.
						<form method="post">{% csrf_token %}
							<input class="btn btn-primary" type="submit" name="leave" value="Unregister">
						</form>
					</p>

				{% else %}
					<p>
						<form method="post">{% csrf_token %}
							<input class="btn btn-primary" type="submit" name="join" value="Join Event">
						</form>
					</p>
				{% endif %}
				
				{% if event.host == request.user %}
					<a href="{% url 'events:edit' event.pk %}" class="btn btn-outline-primary">Edit</a>
					{% include 'events/snippets/delete_modal.html' with event=event %}
					<button class="btn btn-outline-primary" onclick="document.getElementById('{{event.pk}}').style.display='block'">Delete</button>
				{% endif %}
				
				{% if already_playing_message %}<p style="color: red;"><strong>{{ already_playing_message }}</strong></p>{% endif %}
			</div>
			<div class="card-footer text-muted">
				Hosted by {{ event.host }}
			</div>
		</div>
		<!-- End Event Details -->
		
	</div>
</div>



{% endblock content %}

events/templates/events/edit.html
{% extends 'base.html' %}

{% block content %}
<style type="text/css">

    .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
			
				<!-- Title -->
				<div class="form-group">
					<label for="title">Title</label>
					<input class="form-control" type="text" name="title" id="title" placeholder="Title" value="{{form.initial.title}}"required autofocus>
				</div>
				
				<!-- Datetime -->
				<div class="form-group">
					<label for="datetime">Date and time</label>
					<input class="form-control" type="datetime-local" name="datetime" id="datetime" value="{{form.initial.datetime}}" required autofocus>
				</div>
				<!-- fix initial datetime -->
				
				<!-- Location -->
				<div class="form-group">
					<label for="location">Location</label>
					<input class="form-control" type="text" name="location" id="location" placeholder="Location" value="{{form.initial.location}}" required autofocus>
				</div>

				<!-- Description -->
				<div class="form-group">
					<label for="description">Desctiption</label>
					<textarea class="form-control" rows="5" type="text" name="description" id="description" placeholder="Add a description about your event">{{form.initial.description}}</textarea>
				</div>

				<!-- Image -->
				<div class="form-group image-group" id="image_group">
					<img class="img-fluid image" src="{{form.initial.image.url}}"id="image_display">
					<div class="middle">
					    <div class="text">Change image</div>
					</div>
				</div>
				<input type="file" name="image" id="image_file" accept="image/*" onchange="readURL(this)">
				
				<!-- Min_attendees -->
				<div class="form-group">
					<label for="min_attendees">Minimum number of attendees</label>
					<input class="form-control" type="number" name="min_attendees" id="min_attendees" min="1" oninput="changeMaxAttendeesMinVal()" value="{{form.initial.min_attendees}}"required autofocus>
				</div>
				
				<!-- Max_attendees -->
				<div class="form-group">
					<label for="max_attendees">Maximum number of attendees</label>
					<input class="form-control" type="number" name="max_attendees" id="max_attendees" min="1" value="{{form.initial.max_attendees}}"required autofocus>
				</div>
				
				<!-- This function will limit max_attendees value to at least min_attendees value-->
				<script type="text/javascript">
					function changeMaxAttendeesMinVal(){
						var minVal = document.getElementById("min_attendees").value;
						document.getElementById("max_attendees").min = minVal;
						if (document.getElementById("max_attendees").value < minVal){
							document.getElementById("max_attendees").value = minVal;
						}
					}
				</script>
				
				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}
				
				<!-- Submit btn -->
				<div class="row">
					<button class="submit-button col btn btn-lg btn-primary btn-block" type="submit">Update</button>

					<a href="{% url 'account' %}" class="col-xs-6 ml-1 btn btn-lg btn-outline-primary">Cancel</a>
				</div>
				
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('image_group').onclick = function(event){
		document.getElementById('image_file').click();
	};

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
			$('#image_display')
				.attr('src', e.target.result)
		};
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}

events/templates/events/index.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}">

<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.event-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-event-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	
	.lead{
		font-size: 17px;
	}
</style>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Find your event</h1>
  <p class="lead">Look for an event nearby you or create an event with your friends!</p>
</div>


<div class="container">
	<div class="row">
	
		<!-- Event Feed -->
		<div class="left-column col-lg-7 offset-lg-1">
		
			<!-- Top 'create event' bar-->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'logo.jpg' %}" width="72" height="72">
					<p class="lead">Enter text here.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'events:create' %}">Create new event</a></p>
				</div>
			</div>
			
			<!--End Top 'create event' bar -->
			
			<!-- Event List -->
			{% if upcoming_event_list %}
				{% for event in upcoming_event_list %}
					<div class="event-container">
						{% include 'events/snippets/event_snippet.html' with event=event %}
					</div>
				{% endfor %}
			{% else %}
				<div class="event-container">
					{% include 'events/snippets/event_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Event List -->
		
			<!-- Pagination -->
			{% include 'events/snippets/event_pagination.html' with events=events %}		
		</div>
		<!-- End Event Feed -->
			
		<!-- Right 'create event' column-->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">
			<div class="card create-event-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'logo.jpg' %}" width="72" height="72">
				<p class="lead">Enter text here</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'events:create' %}">Create event</a></p>
			</div>
		</div>
		<!--End Right 'create event' column -->
		
	</div>
</div>

{% endblock content %}