events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from account import views


urlpatterns = [
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
    
    #Account links
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('account/',  views.account_view, name='account'),
    path('must_authenticate/',  views.must_authenticate_view, name='must_authenticate'),

    
    #Password reset links
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete'), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

templates/snippets/base_css.html
<style type="text/css">
	body{
		background-color: #f2f2f2;
	}
</style>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
		}
</style>

<!-- FOOTER -->
<div class="d-flex flex-row align-items-center footer">
	<p class="m-auto">Event Manager | 2020</p>
</div>
<!-- END FOOTER -->


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

templates/snippets/header.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<style type="text/css">
	@media (min-width: 768px) {
	  html {
		font-size: 16px;
	  }
	}

	.container {
	  max-width: 960px;
	}

	.card-deck .card {
	  min-width: 220px;
	}
	
	.search-bar{
		max-width: 500px;
		width: 50%;
	}
	
</style>

<!-- HEADER -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
	<h5 class="my-0 mr-md-auto font-weight-normal">
	{% if request.user.is_authenticated %}
		<p>Hello, {{ request.user.username }}</p>
	{% endif %}
	</h5>
  
	<div class="search-bar mt-sm-2 mr-2">
		<form method="get">
			<input type="text" class="form-control" name="q" id="q" placeholder="Search..." value = "{{query}}">
		</form>
	</div>
  
	<nav class="my-2 my-md-0 mr-md-3">
	    {% if request.user.is_authenticated %}
			<a class="p-2 text-dark" href="{% url 'events:index' %}">Home</a> |
			<a class="p-2 text-dark" href="{% url 'account' %}">Account</a> |
			<a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
		{% else %}
			<a class="p-2 text-dark" href="{% url 'events:index' %}">Home</a> |
			<a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
			<a class="btn btn-outline-primary" href="{% url 'register' %}">Register</a>
		{% endif %}
	</nav>
</div>

<!-- <script type="text/javascript"> -->
	<!-- document.getElementById("q").value = "{{query}}" -->
<!-- </script> -->

<!-- END HEADER ->