events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from account import views


urlpatterns = [
    path('events/', include('events.urls', namespace='events')),
    path('admin/', admin.site.urls),
    
    #Account links
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('account/',  views.account_view, name='account'),
    path('must_authenticate/',  views.must_authenticate_view, name='must_authenticate'),

    
    #Password reset links
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete'), name='password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

events/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.core.exceptions import ValidationError
import datetime

# from account.models import Account

def upload_location(instance, filename, **kwargs):
    file_path = 'events/{host_id}/{filename}'.format(
        host_id=str(instance.host.id), filename=filename
    )
    return file_path

class Event(models.Model):
    title           = models.CharField(max_length=50)
    datetime        = models.DateTimeField()
    location        = models.CharField(max_length=100)
    description     = models.TextField(max_length=200)
    image           = models.ImageField(upload_to=upload_location)
    host            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # attendees       = models.ManyToManyField(Account)
    min_attendees   = models.IntegerField()
    max_attendees   = models.IntegerField()
    
    
    def __str__(self):
        return self.title
    
    def clean_date(self):
        date = self.cleaned_data['date']
        if date < datetime.now():
            raise ValidationError("The date cannot be in the past!")
        return date
        
@receiver(models.signals.post_delete, sender=Event)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)
    
    
    

events/forms.py
from django import forms

from .models import Event


class CreateEventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['title', 'datetime', 'location', 'description', 'image', 'min_attendees', 'max_attendees',]
        

class EditEventForm(forms.ModelForm):
    
    class Meta:
        model = Event
        fields = ['title', 'datetime', 'location', 'description', 'image', 'min_attendees', 'max_attendees',]
    
    def save(self, commit=True):
        event = self.instance
        event.title = self.cleaned_data['title']
        event.datetime = self.cleaned_data['datetime']
        event.location = self.cleaned_data['location']
        event.description = self.cleaned_data['description']
        event.min_attendees = self.cleaned_data['min_attendees']
        event.max_attendees = self.cleaned_data['max_attendees']

        if self.cleaned_data['image']:
            event.image = self.cleaned_data['image']
            
        if commit:
            event.save()
            
        return event
        

events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q
from django.core import paginator
from django.contrib import messages

from account.models import Account
from .models import Event
from .forms import CreateEventForm, EditEventForm

EVENTS_PER_PAGE = 1

def index(request):
    context = {}
    query =  ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)
        
    upcoming_event_list = get_event_queryset(query)
    
    #Pagination
    page = request.GET.get('page', 1)
    events_paginator = paginator.Paginator(upcoming_event_list, EVENTS_PER_PAGE)
    
    try:
        upcoming_event_list = events_paginator.page(page)
    except paginator.PageNotAnInteger:
        upcoming_event_list = events_paginator.page(EVENTS_PER_PAGE)
    except paginator.EmptyPage:
        upcoming_event_list = events_paginator.page(events_paginator.num_pages)
    
    context['upcoming_event_list'] = upcoming_event_list
    
    return render(request, 'events/index.html', context)
    
def detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    context = {
        'event': event,
    }
    
    user = request.user

    if request.POST.get("join"):
        if not user.is_authenticated:
            return redirect('must_authenticate')
        if not event.account_set.filter(pk=user.pk).exists():
            event.account_set.add(user)
        
    if request.POST.get("leave"):
        if not user.is_authenticated:
            return redirect('must_authenticate')
        if event.account_set.filter(pk=user.pk).exists():
            event.account_set.remove(user)

        else:
            context['already_playing_message'] = "You are already playing"
            
    return render(request, 'events/detail.html', context)
    
def create(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
        
    form = CreateEventForm(request.POST or None, request.FILES or None,)
    if form.is_valid():
        obj = form.save(commit=False)
        host = Account.objects.filter(email=user.email).first()
        obj.host = host
        obj.save()
        messages.success(request, "Event Created")
        form = CreateEventForm()
        
        if request.POST.get("host_attend", ""):
            obj.account_set.add(user)
            
        return redirect('account')
        
    context['form'] = form
        
    return render(request, 'events/create.html', context)


def edit(request, pk):
    
    context = {}
    
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
 
    event = get_object_or_404(Event, pk=pk)
    
    if event.host != user:
        return HttpResponse("You are not authorized to edit this event.")
    
    if request.POST:
        form = EditEventForm(request.POST or None, request.FILES or None, instance=event)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            messages.success(request, "Updated Event")
            event = obj
            
        return redirect('account')
            
    form = EditEventForm(
        initial = {
            "title":            event.title,
            "datetime":         event.datetime,
            "location":         event.location,
            "description":      event.description,
            "image":            event.image,
            "min_attendees":    event.min_attendees,
            "max_attendees":    event.max_attendees,
        }
    )
    context['form'] = form
    
    return render(request, 'events/edit.html', context)

def delete(request, pk):
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
 
    event = get_object_or_404(Event, pk=pk)
    if event.host != user:
        return HttpResponse("You are not authorized to delete this event.")
    
    if request.POST:
        event.delete()
    
    return redirect('account')
    
    
def get_event_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        events = Event.objects.filter(datetime__gte=timezone.now()).filter(
                Q(title__icontains=q) | 
                Q(description__icontains=q) |
                Q(location__icontains=q) |
                Q(datetime__icontains=q)
            ).distinct().order_by('datetime')
        
        for event in events:
            queryset.append(event)
            
    return list(set(queryset))

events/templates/events/snippets/delete_modal.html
<style type="text/css">
	/* The Modal (background) */
	.modal{
		display: none;
		position: fixed;
		z-index: 10;
		left: 0;
		top: 0;
		width: 100%;
		height: 100%;
		overflow: auto;
		background-color: #474e5d;
		padding-top: 50px;
	}

	/* Modal Content/Box */
	.modal-content {
		background-color: #fefefe;
		margin: 5% auto 15% auto; 
		border: 1px solid #888;
		width: 50%;
	}
	/* Style the horizontal ruler */
	hr {
		border: 1px solid #f1f1f1;
		margin-bottom: 25px;
	}

	/* The Modal Close Button (x) */
	.close {
		position: absolute;
		right: 35px;
		top: 15px;
		font-size: 40px;
		font-weight: bold;
		color: #f1f1f1;
	}

	.close:hover,
	.close:focus {
		color: #f44336;
		cursor: pointer;
	}

	/* Clear floats */
	.clearfix::after {
		content: "";
		clear: both;
		display: table;
	}
</style>

<!-- Delete Modal -->
<div id="{{event.pk}}" class="modal">
	<span onclick="document.getElementById('{{event.pk}}').style.display='none'" class="close" title="Close">&times;</span>
	<div class="modal-content container">
		<h2>Delete Event</h2>
		<p>Are you sure you want to delete this event?</p>
		<div class="clearfix row">
			<button class="btn btn-light" class="btn btn-outline-primary" onclick="document.getElementById('{{event.pk}}').style.display='none'">Cancel</button>
			<form action="{% url 'events:delete' event.pk %}" method="post">{% csrf_token %}	
				<input class="btn btn-danger" name="delete" type="submit" value="Delete">
			</form>
		</div>
	</div>
</div>

<script>
// Get the modal
var modal = document.getElementById('{{event.pk}}');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>
<!-- End Delete Modal -->

events/templates/events/snippets/event_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if upcoming_event_list.has_previous %}
        <li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ upcoming_event_list.paginator.number }}">&laquo; First</a>
		</li>
		<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ upcoming_event_list.previous_page_number }}">Previous</a>
		</li>
    {% endif %}

	{% for i in upcoming_event_list.paginator.page_range %}
		{% if upcoming_event_list.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if upcoming_event_list.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ upcoming_event_list.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ upcoming_event_list.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

events/templates/events/snippets/event_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>



{% if event %}
<div class="container">
	<div class="row">

		<!-- Event -->
		<!-- <div class="card m-auto" style="width: 18rem;"> -->
			<!-- <a href="{% url 'events:detail' event.pk %}"> -->
				<!-- <img class="card-img-top" src="{{event.image.url}}"> -->
			<!-- </a>		 -->
			<!-- <div class="card-body mt-2 mb-2"> -->
				<!-- <a href="{% url 'events:detail' event.pk %}"> -->
					<!-- <h2 class="card-title">{{event.title}}</h2> -->
				<!-- </a> -->
				<!-- <p class="card-text">{{event.location}}</p> -->
				<!-- <p class="card-text">{{event.datetime}}</p> -->
				<!-- <p class="card-text">{{event.description|safe|truncatechars:180}}</p> -->
				<!-- <a href="{% url 'events:detail' event.pk %}" class="btn btn-primary">Details</a> -->
				<!-- {% if event.host == request.user %} -->
					<!-- <a href="{% url 'events:edit' event.pk %}" class="btn btn-primary">Update</a> -->
				<!-- {% endif %} -->
			<!-- </div> -->
			
			<!-- <div class="card-footer text-muted"> -->
			  <!-- Hosted by {{event.host}} -->
			<!-- </div> -->
		<!-- </div> -->
		
		<div class="card m-auto flex-row flex-wrap">
			<a href="{% url 'events:detail' event.pk %}">
				<img class="card-header border-0" style="width: 18rem;" src="{{event.image.url}}">
			</a>		
			<div class="card-block mt-2 mb-2 px-3">
				<a href="{% url 'events:detail' event.pk %}">
					<h4 class="card-title">{{event.title}}</h4>
				</a>
				<p class="card-text"><strong>Where? </strong>{{event.location}}</p>
				<p class="card-text"><strong>When? </strong>{{event.datetime}}</p>
				<p class="card-text">{{event.description|safe|truncatechars:180}}</p>
				<a href="{% url 'events:detail' event.pk %}" class="btn btn-primary">Details</a>
				{% if event.host == request.user %}
					<a href="{% url 'events:edit' event.pk %}" class="btn btn-outline-primary">Edit</a>
					{% include 'events/snippets/delete_modal.html' with event=event %}
					<button class="btn btn-outline-primary" onclick="document.getElementById('{{event.pk}}').style.display='block'">Delete</button>
				{% endif %}
			</div>
			<div class="w-100"></div>
			<div class="card-footer w-100 text-muted">
			  Hosted by {{event.host}}
			</div>
		</div>
	</div>
</div>
{% else %}
<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">
					No results
				</h2>
				<p class="card-text"> There were no results matching your search: "{{query}}".</p>
			</div>
		</div>
	</div>
</div>
{% endif %}